### ISSUE TITLE
Not possible to publish international publications with sme

### ISSUE THREAD

**Issue by pie-ai** [EFA-FHB/eforms-validator-core#155]
With Version 1.0.12 the rules seam to only allow german publications as, if I do understand it right, the changes in
https://github.com/EFA-FHB/eforms-validator-core/compare/1.0.11...1.0.12

>    
>    <assert id="BR-DE-26" test="
>        
>
>         if (cbc:SMESuitableIndicator/text() = 'true' or cbc:SMESuitableIndicator/text() = '1')
>         then
>           (starts-with(cbc:Note[./@languageID = 'DEU']/text()/normalize-space(.), '#Besonders geeignet für:freelance#') or
>           starts-with(cbc:Note[./@languageID = 'DEU']/text()/normalize-space(.), '#Besonders geeignet für:startup#') or
>           starts-with(cbc:Note[./@languageID = 'DEU']/text()/normalize-space(.), '#Besonders geeignet für:selbst#')
>           )
> else
>           true()" role="error">[BR-DE-26-Part] If SMESuitableIndicator is true or 1, BT-300 /cac:ProcurementProject/cbd:Note needs to start with #Besonders geeignet für:(freelance|startup|selbst)#, free-text can follow.

require a german note. If rendered additionally other problems get raised.

**Comment by pie-ai** [comment]
We got feedback via Email from Bundesdruckerei and their solution is to publish the publication in german and english. That might be a solution but it is not acceptable to be forced to always publish publications in german.

Please have a look at the details, our customer have a great problem and might be forced to publish invalid indicators or delay publications of important procedures.

**Comment by pie-ai** [comment]
Some technical details to understand the problem. If an internationally operating organization publishes publications, it uses the english language. If we would additionally add sme details to the text in german language, we would need to publish a lot of fields multilingual as rules like

> (every $lg in (cbc:Note/@languageID) satisfies $lg = (/*/cbc:NoticeLanguageCode, /*/cac:AdditionalNoticeLanguage/cbc:ID)) or count(cbc:Note) = 0

force us to not only publish one field in german but almost all fields.

**Comment by pie-ai** [comment]
In https://github.com/EFA-FHB/ozg-vermittlungsdienst-doku/blob/main/faq.md#allgemeine-fragen steht:

> Gibt es Vorgaben zur Sprache der Bekanntmachung oder Mehrsprachigkeit?
> Es gibt zwar keine Aussage zur Wahl der Sprache von Ausschreibungen in der Vergabeordnung, jedoch ist nach § 23 Abs. 1 Verwaltungsverfahrensgesetz (VwVfG) die Amtssprache deutsch. Dementsprechend ist zu erwarten, dass deutsche Behörden ihre Unterlagen immer mindestens in deutscher Sprache ausfertigen müssen. Mehrsprachigkeit ist natürlich möglich und erlaubt.

Meiner Meinung nach sind Sektorenauftraggeber keine Behörden und ausschließlich dieses Feld macht Probleme.

**Comment by JanEisen** [comment]
Hello,
sorry for the late response. 

**This rule will be temporarily disabled to allow publication of english only notices.**

A Bugfix is being evaluated and in eForms-DE 1.2 there will be no rule that requires the german language.
