### ISSUE TITLE
Validation of rule BR-BT-00539-0200 sometimes depends on the ordering of 'Award criterion number' (BT-541)

### ISSUE THREAD

**Issue by markus-csx** [EFA-FHB/eforms-validator-core#176]
When validating [not_working.xml.txt](https://github.com/EFA-FHB/eforms-validator-core/files/14755393/not_working.xml.txt) the staging-environment [validator.staging-ozg-vermittlungsdienst.de ](https://validator.staging-ozg-vermittlungsdienst.de)returns:

```
{
  "valid": false,
  "validatedEformsVersion": "eforms-de-1.1.0",
  "warnings": [...],
  "errors": [
    {
      "type": "SCHEMATRON",
      "description": "The sum of all 'Award criterion number' (BT-541) of type 'Weight (percentage, exact)' must equal 100 for each criteria in the lot",
      "rule": "rule|text|BR-BT-00539-0200",
      "ruleContent": "sum(cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter/efbc:ParameterNumeric[../efbc:ParameterCode[@listName='number-weight']/normalize-space(text()) = 'per-exa']) = 100 or not(cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter/efbc:ParameterNumeric[../efbc:ParameterCode[@listName='number-weight']/normalize-space(text()) = 'per-exa'])",
      "path": "/can:ContractAwardNotice/cac:ProcurementProjectLot/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion"
    }
  ]
}
```

In contrast the file [working.xml.txt](https://github.com/EFA-FHB/eforms-validator-core/files/14755392/working.xml.txt) is successfully validated.

The only difference between the files is the ordering of 'Award criterion number'.

The different results of the validation do not seem logical and the rule itself does not reference any order of 'Award criterion number'.

**Comment by JolantaMatulione** [comment]
Hello, 
We send this question to TED, because it does not depend on us this time. When we will get answer from them we will update here too.

**Comment by JolantaMatulione** [comment]
Hello, 
Answer from TED is discussed here: https://github.com/OP-TED/eForms-SDK/issues/906
