### ISSUE TITLE
Nicht lauffähig unter Java 11 da 

### ISSUE THREAD

**Issue by pie-ai** [EFA-FHB/eforms-validator-core#78]
Scheinbar kann man das Projekt mit Java 17 auf Java 11 Niveau kompilieren, leider wird dann aber zumindest eine nicht existierende Methode referenziert:

```
java.lang.NoSuchMethodError: 'java.lang.String java.lang.String.formatted(java.lang.Object[])'
at com.nortal.efafhb.eforms.validator.validation.service.ValidatorUtil.<clinit>(ValidatorUtil.java:42)
```

Zumindest um das Problem zu lösen, könnte man

```
   protected static final List<String> EXCLUDED_SCHEMATRON_RULES_DE =
       readExcludedSchematronRules(String.format(EXCLUDED_SCHEMATRON_RULES_DE_RESOURCE_PATH, "de"));
```

statt 

```  
protected static final List<String> EXCLUDED_SCHEMATRON_RULES_DE = readExcludedSchematronRules("schematron/%s/excluded_rules.txt".formatted("de"));

```
Das betrifft allerdings viele Stellen im Code (zumindest wenn ich mal genauer drauf gucke. Am saubersten wäre es, wenn man den Java 11 kompatiblen Code auch direkt mit Java 11 kompiliert. Wenn das gewünscht ist, gab es doch einen Branch, der dieses ermöglichen soll. Kenne den Verbleib aber nicht.

**Comment by deversbpv** [comment]
Kann ich bestätigen.

**Comment by DanelRod** [comment]
Changes in progress 
https://github.com/EFA-FHB/eforms-validator-core/pull/86
